<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Unibiz Gutenverse Home Clients', 'unibiz' ),
	'categories' => array( 'unibiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1260"},"gap":"no","elementId":"guten-nnWPq8","padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"150","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"100","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"80","left":"0"}}}} -->
<div class="section-wrapper" data-id="nnWPq8"><section class="wp-block-gutenverse-section guten-element guten-section guten-nnWPq8 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-vCq1U3"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vCq1U3"><div class="guten-column-wrapper" data-id="vCq1U3"><!-- wp:gutenverse/text-editor {"elementId":"guten-eA5zSm","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-button-primary","size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"600","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"}},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}}} -->
<div class="guten-element gutenverse-text-editor guten-eA5zSm"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Trusted by <a href="#">4,000+</a> leading companies</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/logo-slider {"elementId":"guten-fJQGOl","logos":[{"title":"One","_key":"RUpidE","src":{"id":1106,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-1.webp"},"lazyLoad":true},{"title":"Two","_key":"bNVT6m","src":{"id":1107,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-2.webp"},"lazyLoad":true},{"title":"Three","_key":"PbdG1X","src":{"id":1108,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-3.webp"},"lazyLoad":true},{"title":"Four","_key":"TiL7Ng","src":{"id":1109,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-4.webp"},"lazyLoad":true},{"_key":"I4gIpL","title":"Six","src":{"id":1110,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-5.webp"},"hoverSrc":[],"lazyLoad":true},{"title":"Five","_key":"fLhNZ8","src":{"id":1111,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-6.webp"},"hoverSrc":[],"lazyLoad":true}],"imageFixHeight":true,"imageHeight":{"Desktop":"24"},"imageFit":{"Desktop":"scale-down"},"imagePadding":{"Desktop":{"unit":"px","dimension":{"top":""}}},"imageMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"transitionDuration":{"Desktop":"0.3"},"spacing":{"Desktop":"64","Mobile":"32","Tablet":"48"},"itemShowed":{"Desktop":"5","Tablet":"4","Mobile":"3"},"autoplay":true,"autoplayTimeout":3200,"loop":true,"opacity":"0.3","hoverOpacity":"1","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element guten-client-logo grid-desktop-3 guten-fJQGOl arrow-bottom-edge"><div class="client-list"><div id="guten-fJQGOl" class="swiper-container" data-loop="true" data-autoplay="true" data-timeout="3200" data-nav="false" data-arrow="false" data-breakpoints="{&quot;0&quot;:{&quot;spaceBetween&quot;:32,&quot;slidesPerView&quot;:3},&quot;768&quot;:{&quot;spaceBetween&quot;:48,&quot;slidesPerView&quot;:4},&quot;1024&quot;:{&quot;spaceBetween&quot;:64,&quot;slidesPerView&quot;:5}}"><div class="swiper-wrapper"><div class="image-list swiper-slide"><div class="content-image"><img class="main-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-1.webp" alt="One" loading="lazy"/><img class="hover-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-1.webp" alt="One" loading="lazy"/></div></div><div class="image-list swiper-slide"><div class="content-image"><img class="main-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-2.webp" alt="Two" loading="lazy"/><img class="hover-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-2.webp" alt="Two" loading="lazy"/></div></div><div class="image-list swiper-slide"><div class="content-image"><img class="main-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-3.webp" alt="Three" loading="lazy"/><img class="hover-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-3.webp" alt="Three" loading="lazy"/></div></div><div class="image-list swiper-slide"><div class="content-image"><img class="main-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-4.webp" alt="Four" loading="lazy"/><img class="hover-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-4.webp" alt="Four" loading="lazy"/></div></div><div class="image-list swiper-slide"><div class="content-image"><img class="main-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-5.webp" alt="Six" loading="lazy"/><img class="hover-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-5.webp" alt="Six" loading="lazy"/></div></div><div class="image-list swiper-slide"><div class="content-image"><img class="main-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-6.webp" alt="Five" loading="lazy"/><img class="hover-image" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/client-logo-unibiz-6.webp" alt="Five" loading="lazy"/></div></div></div></div></div></div>
<!-- /wp:gutenverse/logo-slider -->

<!-- wp:gutenverse/spacer {"elementId":"guten-KcxFPa","space":{"Desktop":{"unit":"px","point":"51"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-51","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Desktop":2},"pointer":{"pointer":{"Desktop":"none"}},"background":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":true,"opacity":0,"id":3,"offset":"0.250"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":6,"offset":"0.750"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":5,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"90"}} -->
<div class="guten-element guten-spacer guten-KcxFPa"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
