<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Unibiz Gutenverse Home Services', 'unibiz' ),
	'categories' => array( 'unibiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1260","Tablet":""},"gap":"no","elementId":"guten-JLCPkz","padding":{"Desktop":{"unit":"px","dimension":{"top":"150","right":"20","bottom":"150","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"20","bottom":"100","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"20","bottom":"80","left":"20"}}}} -->
<div class="section-wrapper" data-id="JLCPkz"><section class="wp-block-gutenverse-section guten-element guten-section guten-JLCPkz layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"forceColumnHundred":{"Desktop":true,"previousValues":{"Tablet":"inherit"},"Tablet":true,"Mobile":true},"elementId":"guten-ksyQgQ","verticalAlign":{"Desktop":"flex-end"},"horizontalAlign":{"Desktop":"space-between"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"60","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"50","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ksyQgQ"><div class="guten-column-wrapper" data-id="ksyQgQ"><!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-07M9xB"} -->
<div class="section-wrapper" data-id="07M9xB"><section class="wp-block-gutenverse-section guten-element guten-section guten-07M9xB layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-i2a7Dy"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-i2a7Dy"><div class="guten-column-wrapper" data-id="i2a7Dy"><!-- wp:gutenverse/heading {"elementId":"guten-pmS1Sx","color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.25"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"512"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-pmS1Sx">World-Class Service That Helps You Grow</h2>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-TZXYWP","verticalAlign":{"Desktop":"flex-end"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"124"}},"Tablet":{"unit":"px","dimension":{"left":"80"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TZXYWP"><div class="guten-column-wrapper" data-id="TZXYWP"><!-- wp:gutenverse/text-editor {"elementId":"guten-w13VL9","textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"px","point":"505"}}} -->
<div class="guten-element gutenverse-text-editor guten-w13VL9"><div class="text-content-inner"><!-- wp:paragraph -->
<p>From strategy to execution, our services are designed to support your growth at every stage. We deliver reliable, high quality solutions that meet to your business needs.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50},"forceColumnHundred":{"Desktop":true,"previousValues":{"Tablet":"inherit"},"Tablet":true,"Mobile":true},"elementId":"guten-95NRcF"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-95NRcF"><div class="guten-column-wrapper" data-id="95NRcF"><!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-fo5VKk"} -->
<div class="section-wrapper" data-id="fo5VKk"><section class="wp-block-gutenverse-section guten-element guten-section guten-fo5VKk layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100},"elementId":"guten-YwVUir","padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-YwVUir"><div class="guten-column-wrapper" data-id="YwVUir"><!-- wp:gutenverse/wrapper {"elementId":"guten-bzS3rK","border":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}},"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}} -->
<div class="guten-element guten-wrap-helper no-margin guten-bzS3rK"><div class="guten-inner-wrap" data-id="bzS3rK"><!-- wp:gutenverse/image {"elementId":"guten-63O54x","imgSrc":{"media":{"imageId":612,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-1-img.webp","orientation":"landscape"},"medium":{"height":224,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-1-img.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-1-img.webp","height":566,"width":758,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"6","bottom":"6","left":"6"}}}},"background":{"type":"gradient","gradientColor":[{"color":"rgba(247, 244, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(247, 244, 255, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}]},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-63O54x"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-1-img.webp" height="566" width="758" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-PdVnGi","separateButtonLink":false,"title":"Web Design","titleTag":"h3","description":"Crafting visually striking and user friendly designs that elevate your online presence.","iconType":"none","imageWidthResponsive":{"Tablet":null,"Mobile":null,"Desktop":""},"image":{"id":339,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-img-1.webp"},"imageFit":"cover","iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"none","width":1,"color":{"type":"variable","id":"gv-color-border"}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"22","right":"89","bottom":"43","left":"89"}},"Tablet":{"unit":"px","dimension":{"right":"248","left":"248"}},"Mobile":{"unit":"px","dimension":{"right":"45","left":"45"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"iconStyleMode":"gradient","iconBgGradient":{"type":"gradient","gradientColor":[{"color":"rgba(247, 244, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(247, 244, 255, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}]},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"6","bottom":"6","left":"6"}}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"12","left":"20"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"700"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"20","left":"20"}}},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"parentSelector":".guten-PdVnGi:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-PdVnGi guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Web Design</h3><p class="icon-box-description">Crafting visually striking and user friendly designs that elevate your online presence.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100},"elementId":"guten-r1t7EY","padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-r1t7EY"><div class="guten-column-wrapper" data-id="r1t7EY"><!-- wp:gutenverse/wrapper {"elementId":"guten-YZKI50","border":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}},"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}} -->
<div class="guten-element guten-wrap-helper no-margin guten-YZKI50"><div class="guten-inner-wrap" data-id="YZKI50"><!-- wp:gutenverse/image {"elementId":"guten-iokWIL","imgSrc":{"media":{"imageId":613,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-2-img.webp","orientation":"landscape"},"medium":{"height":225,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-2-img.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-2-img.webp","height":566,"width":756,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"6","bottom":"6","left":"6"}}}},"background":{"type":"gradient","gradientColor":[{"color":"rgba(247, 244, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(247, 244, 255, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}]},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-iokWIL"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-2-img.webp" height="566" width="756" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-WNJoub","separateButtonLink":false,"title":"Digital Marketing","titleTag":"h3","description":"Driving growth through data-driven strategies that connect you with the right audience.","iconType":"none","imageWidth":379,"imageHeight":283,"imageWidthResponsive":{"Tablet":718,"Mobile":298},"image":{"id":340,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-img-2.webp"},"iconPosition":"top","align":{"Desktop":"flex-start","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"none","width":1,"color":{"type":"variable","id":"gv-color-border"}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"13","right":"75","bottom":"58","left":"75"}},"Tablet":{"unit":"px","dimension":{"right":"240","left":"240"}},"Mobile":{"unit":"px","dimension":{"right":"45","left":"45"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"iconStyleMode":"gradient","iconBgGradient":{"type":"gradient","gradientColor":[{"color":"rgba(247, 244, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(247, 244, 255, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}]},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"6","bottom":"6","left":"6"}}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"12","left":"20"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"700"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"20","left":"20"}}},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"parentSelector":".guten-WNJoub:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-WNJoub guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Digital Marketing</h3><p class="icon-box-description">Driving growth through data-driven strategies that connect you with the right audience.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100},"elementId":"guten-GqBddM","padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GqBddM"><div class="guten-column-wrapper" data-id="GqBddM"><!-- wp:gutenverse/wrapper {"elementId":"guten-9xYXc8","border":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}},"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}} -->
<div class="guten-element guten-wrap-helper no-margin guten-9xYXc8"><div class="guten-inner-wrap" data-id="9xYXc8"><!-- wp:gutenverse/image {"elementId":"guten-b64LcR","imgSrc":{"media":{"imageId":614,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-3-img.webp","orientation":"landscape"},"medium":{"height":224,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-3-img.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-3-img.webp","height":566,"width":758,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"6","bottom":"6","left":"6"}}}},"background":{"type":"gradient","gradientColor":[{"color":"rgba(247, 244, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(247, 244, 255, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}]},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-b64LcR"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-3-img.webp" height="566" width="758" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-C3He4E","separateButtonLink":false,"title":"Web Development","titleTag":"h3","description":"We develop your website fast, secure, and scalable that match to your business goals.","iconType":"none","imageWidth":379,"imageHeight":283,"imageWidthResponsive":{"Tablet":718,"Mobile":298},"image":{"id":341,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-services-img-3.webp"},"iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"none","width":1,"color":{"type":"variable","id":"gv-color-border"}}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"7","right":"72","bottom":"34","left":"65"}},"Tablet":{"unit":"px","dimension":{"right":"240","left":"240"}},"Mobile":{"unit":"px","dimension":{"right":"45","left":"45"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"iconStyleMode":"gradient","iconBgGradient":{"type":"gradient","gradientColor":[{"color":"rgba(247, 244, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(247, 244, 255, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}]},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"6","bottom":"6","left":"6"}}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"12","left":"20"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"700"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"20","left":"20"}}},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"parentSelector":".guten-C3He4E:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-C3He4E guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-body"><h3 class="title">Web Development</h3><p class="icon-box-description">We develop your website fast, secure, and scalable that match to your business goals.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
