<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Unibiz Gutenverse Home Authority', 'unibiz' ),
	'categories' => array( 'unibiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1260","Tablet":""},"gap":"no","elementId":"guten-bTwfgr","background":{"type":"default","color":{"type":"variable","id":"gv-color-background-secondary"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","right":"20","bottom":"120","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"20","bottom":"100","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"20","bottom":"80","left":"20"}}}} -->
<div class="section-wrapper" data-id="bTwfgr"><section class="wp-block-gutenverse-section guten-element guten-section guten-bTwfgr layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":48.8,"Tablet":100},"elementId":"guten-R4P7ix","order":{"Desktop":"1","Tablet":2}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-R4P7ix"><div class="guten-column-wrapper" data-id="R4P7ix"><!-- wp:gutenverse/image {"elementId":"guten-b5wGqI","imgSrc":{"media":{"imageId":309,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-statistics-e1755584861696.webp","orientation":"landscape"},"medium":{"height":245,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-statistics-e1755584861696.webp","orientation":"landscape"},"large":{"height":836,"width":1024,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-statistics-e1755584861696.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-statistics-e1755584861696.webp","height":1003,"width":1228,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"height":{"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}},"imageFit":{"Desktop":"cover"},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-b5wGqI"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-statistics-e1755584861696.webp" height="1003" width="1228" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":51.2,"Tablet":100},"elementId":"guten-wZ3TYl","verticalAlign":{"Desktop":"center"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"100"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"50","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-wZ3TYl"><div class="guten-column-wrapper" data-id="wZ3TYl"><!-- wp:gutenverse/heading {"elementId":"guten-M2xFpt","color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.25"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"512"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-M2xFpt">We Dedicate Our Time To Deliver Great Results</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-VoDAIZ","textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"60","left":"0"}}},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"415"}}} -->
<div class="guten-element gutenverse-text-editor guten-VoDAIZ"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Every number tells a story of commitment, consistency, and impact. From successful projects to satisfied clients, our results reflect the time and our effort we invest in delivering quality solutions that drive real growth. These milestones aren’t just metrics—they’re proof of the trust our clients.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-uYukKi"} -->
<div class="section-wrapper" data-id="uYukKi"><section class="wp-block-gutenverse-section guten-element guten-section guten-uYukKi layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"elementId":"guten-RcFhoV","padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-RcFhoV"><div class="guten-column-wrapper" data-id="RcFhoV"><!-- wp:gutenverse/fun-fact {"elementId":"guten-aoZYN5","iconType":"none","prefix":"","safeNumber":"350","suffix":"","title":"Satisfied Clients","showSupper":true,"superColor":{"type":"variable","id":"gv-color-accent"},"superTypography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"52"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"600","spacing":{"Desktop":"-0.02"}},"superTop":{"Desktop":"0"},"superSpace":{"Desktop":""},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-accent"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"numberTypography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"52"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"600","spacing":{"Desktop":"-0.02"}},"titleTypography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}}},"numberBottomSpace":{"Desktop":"12"},"numberRightSpace":{"Desktop":"5","Mobile":"2"}} -->
<div class="guten-element guten-aoZYN5 guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content block"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number-format="" data-safe="350" data-number="" data-duration="3500" data-number-spaces="{&quot;Desktop&quot;:&quot;5&quot;,&quot;Mobile&quot;:&quot;2&quot;}"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Satisfied Clients</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"elementId":"guten-DARwyb"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DARwyb"><div class="guten-column-wrapper" data-id="DARwyb"><!-- wp:gutenverse/fun-fact {"elementId":"guten-ddprRu","iconType":"none","prefix":"","safeNumber":"120","suffix":"","title":"Projects Completed","showSupper":true,"supper":"K","superColor":{"type":"variable","id":"gv-color-accent"},"superTypography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"52"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"600","spacing":{"Desktop":"-0.02"}},"superTop":{"Desktop":"0"},"superSpace":{"Desktop":""},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-accent"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"numberTypography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"52"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"600","spacing":{"Desktop":"-0.02"}},"titleTypography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}}},"numberBottomSpace":{"Desktop":"12"},"numberRightSpace":{"Desktop":"5","Mobile":"2"}} -->
<div class="guten-element guten-ddprRu guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content block"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number-format="" data-safe="120" data-number="" data-duration="3500" data-number-spaces="{&quot;Desktop&quot;:&quot;5&quot;,&quot;Mobile&quot;:&quot;2&quot;}"></span><span class="suffix"></span><sup class="super">K</sup></div><span class="title">Projects Completed</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
