<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Unibiz Gutenverse Home Blog', 'unibiz' ),
	'categories' => array( 'unibiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1260"},"gap":"no","elementId":"guten-VXlbzT","padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"150","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"68","left":"20"}}}} -->
<div class="section-wrapper" data-id="VXlbzT"><section class="wp-block-gutenverse-section guten-element guten-section guten-VXlbzT layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-EnbrPK"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-EnbrPK"><div class="guten-column-wrapper" data-id="EnbrPK"><!-- wp:gutenverse/heading {"elementId":"guten-EvhluN","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.25"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"60","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"512"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-EvhluN">Catch Up on Our Latest Updates</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/post-block {"elementId":"guten-dDVELj","column":{"Desktop":"3","Tablet":"1"},"excerptLength":"9","readmoreEnabled":false,"metaAuthorEnabled":false,"metaDateIcon":"","postblockType":"type-2","postItemPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"22","left":"10"}}},"postItemBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}}},"thumbnailMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"thumbnailBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"6","bottom":"6","left":"6"}}}},"thumbnailHeight":{"Desktop":"270"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}},"categoryColor":{"type":"variable","id":"gv-color-accent"},"categoryTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"categoryBackground":{"type":"variable","id":"gv-color-background-tertiary"},"categoryMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"categoryPadding":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"12","bottom":"6","left":"12"}}},"categoryBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"6","bottom":"6","left":"6"}}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"26"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"700"},"titleColorHover":{"type":"variable","id":"gv-color-accent"},"excerptColor":{"type":"variable","id":"gv-color-text-secondary"},"excerptTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"metaTypography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"12"}}},"metaColor":{"type":"variable","id":"gv-color-text-placeholder"},"metaMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"metaAuthorIconSpacing":{"Desktop":"0"},"metaDateIconSpacing":{"Desktop":"0"}} -->
<div class="guten-element guten-post-block guten-dDVELj"></div>
<!-- /wp:gutenverse/post-block --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
