<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Unibiz Gutenverse Home About', 'unibiz' ),
	'categories' => array( 'unibiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1260"},"gap":"no","elementId":"guten-9jxaJR","padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}}} -->
<div class="section-wrapper" data-id="9jxaJR"><section class="wp-block-gutenverse-section guten-element guten-section guten-9jxaJR layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-vgtvtf","padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"50","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vgtvtf"><div class="guten-column-wrapper" data-id="vgtvtf"><!-- wp:gutenverse/heading {"elementId":"guten-Z05ltj","color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.25"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"60","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"490"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-Z05ltj">Our Clients Trust Us We Deliver Results</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-Yz9Qki","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}}} -->
<div class="section-wrapper" data-id="Yz9Qki"><section class="wp-block-gutenverse-section guten-element guten-section guten-Yz9Qki layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-3t0Iif","padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"16","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3t0Iif"><div class="guten-column-wrapper" data-id="3t0Iif"><!-- wp:gutenverse/icon-box {"elementId":"guten-PZKOEh","separateButtonLink":false,"title":"Creative Solutions","titleTag":"h3","description":"We approach every challenge with fresh ideas that to meet your goals.","iconType":"image","icon":"gtn gtn-puzzle-piece-solid","iconSize":{"Desktop":"20"},"imageWidth":48,"imageHeight":48,"image":{"id":301,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-1.webp"},"imageAlt":"image-creative","iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"24","left":"0"}}},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconBgColor":{"type":"variable","id":"gv-color-background-secondary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"12","left":"0"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"700"},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"lazyLoad":true,"parentSelector":".guten-PZKOEh:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-PZKOEh guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-1.webp" alt="image-creative" loading="lazy"/></div></div><div class="icon-box icon-box-body"><h3 class="title">Creative Solutions</h3><p class="icon-box-description">We approach every challenge with fresh ideas that to meet your goals.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-W7moDg","padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"16"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-W7moDg"><div class="guten-column-wrapper" data-id="W7moDg"><!-- wp:gutenverse/icon-box {"elementId":"guten-sStiPD","separateButtonLink":false,"title":"Smart Design","titleTag":"h3","description":"Our layouts are seamlessly crafted by balancing the visual and usability.","iconType":"image","icon":"gtn gtn-puzzle-piece-solid","iconSize":{"Desktop":"20"},"imageWidth":48,"imageHeight":48,"image":{"id":302,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-2.webp"},"imageAlt":"image-design","iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"24","left":"0"}}},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconBgColor":{"type":"variable","id":"gv-color-background-secondary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"12","left":"0"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"700"},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"lazyLoad":true,"parentSelector":".guten-sStiPD:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-sStiPD guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-2.webp" alt="image-design" loading="lazy"/></div></div><div class="icon-box icon-box-body"><h3 class="title">Smart Design</h3><p class="icon-box-description">Our layouts are seamlessly crafted by balancing the visual and usability.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-2X6ay4"} -->
<div class="section-wrapper" data-id="2X6ay4"><section class="wp-block-gutenverse-section guten-element guten-section guten-2X6ay4 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-I5uAbc","padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"16","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-I5uAbc"><div class="guten-column-wrapper" data-id="I5uAbc"><!-- wp:gutenverse/icon-box {"elementId":"guten-WGCFJ0","separateButtonLink":false,"title":"Solid Feature","titleTag":"h3","description":"Built with performance, every feature is reliable, practical, and ready to scale.","iconType":"image","icon":"gtn gtn-puzzle-piece-solid","iconSize":{"Desktop":"20"},"imageWidth":48,"imageHeight":48,"image":{"id":303,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-3.webp"},"imageAlt":"image-feature","iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"24","left":"0"}}},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconBgColor":{"type":"variable","id":"gv-color-background-secondary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"12","left":"0"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"700"},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"lazyLoad":true,"parentSelector":".guten-WGCFJ0:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-WGCFJ0 guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-3.webp" alt="image-feature" loading="lazy"/></div></div><div class="icon-box icon-box-body"><h3 class="title">Solid Feature</h3><p class="icon-box-description">Built with performance, every feature is reliable, practical, and ready to scale.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-K9OGED","padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"16"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-K9OGED"><div class="guten-column-wrapper" data-id="K9OGED"><!-- wp:gutenverse/icon-box {"elementId":"guten-hd9MpP","separateButtonLink":false,"title":"Dedicated Support","titleTag":"h3","description":"Dedicated friendly help from our team that’s committed to your success.","iconType":"image","icon":"gtn gtn-puzzle-piece-solid","iconSize":{"Desktop":"20"},"imageWidth":48,"imageHeight":48,"image":{"id":304,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-4.webp"},"imageAlt":"image-support","iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"24","left":"0"}}},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconBgColor":{"type":"variable","id":"gv-color-background-secondary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"12","left":"0"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"weight":"700"},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"lazyLoad":true,"parentSelector":".guten-hd9MpP:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-hd9MpP guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-4.webp" alt="image-support" loading="lazy"/></div></div><div class="icon-box icon-box-body"><h3 class="title">Dedicated Support</h3><p class="icon-box-description">Dedicated friendly help from our team that’s committed to your success.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-9XDKun","padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"124"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-9XDKun"><div class="guten-column-wrapper" data-id="9XDKun"><!-- wp:gutenverse/image {"elementId":"guten-cgNwTM","imgSrc":{"media":{"imageId":307,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-img.webp","orientation":"landscape"},"medium":{"height":300,"width":279,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-img.webp","orientation":"portrait"},"large":{"height":1024,"width":952,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-img.webp","orientation":"portrait"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-img.webp","height":1088,"width":1012,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"px","point":""},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"height":{"Tablet":{"unit":"px","point":"600"},"Desktop":{"unit":"px"},"Mobile":{"unit":"px","point":"300"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}},"imageFit":{"Tablet":"cover","Mobile":"cover"},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-cgNwTM"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/unibiz-benefits-img.webp" height="1088" width="1012" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
